### ISSUE TITLE
Re-host the join Slack link

### ISSUE THREAD

**Issue by elisechant** [designsystemau/TSC#9]
- [ ] Create Slack invitation endpoint slack.designsystemau.org
- [ ] @elisechant can set up the subdomain alias or ask Elise for access

**Comment by dominikwilkowski** [comment]
This is the current repo for the inviter: https://github.com/govau/guides-slack-invite-automation

**Comment by dominikwilkowski** [comment]
This invite link never expires and allows for 2000 people to join: https://join.slack.com/t/govau-guides/shared_invite/zt-ti4e4rcl-x7212CuhA3eQtAxzuJqUbw

Maybe we include a badge in each README.md file in each repo with that link and don't worry for now about an auto-invite app?
